export const FETCH_REPOSITORIES_START = 'FETCH_REPOSITORIES_START'

export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'

export const FETCH_REPOSITORIES_FAIL = 'FETCH_REPOSITORIES_FAIL'

export const FETCH_LANGUAGES_START = 'FETCH_LANGUAGES_START'

export const FETCH_LANGUAGES_SUCCESS = 'FETCH_LANGUAGES_SUCCESS'

export const FETCH_LANGUAGES_FAIL = 'FETCH_CONTRIBUTORS_FAIL'

export const FETCH_CONTRIBUTORS_START = 'FETCH_CONTRIBUTORS_START'

export const FETCH_CONTRIBUTORS_SUCCESS = 'FETCH_CONTRIBUTORS_SUCCESS'

export const FETCH_CONTRIBUTORS_FAIL = 'FETCH_CONTRIBUTORS_FAIL'

export const SET_QUERY = 'SET_QUERY'
